### ISSUE TITLE
gseNCG for mouse genome 

### ISSUE THREAD

**Issue by Hallalster** [GuangchuangYu/enrichplot#16]
Hello,
Can we run gseNCG function on a vector of sorted genes ( values = log2foldchange,vector names= entrez ID)
Data  generated from differential expression analysis results of mus musculus RNA-seq samples (mm10)
Thank you 
P.S. : i am getting this error 
preparing geneSet collections...
--> Expected input gene ID: 4751,673,9700,9794,472,58508
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....

**Comment by GuangchuangYu** [comment]
the `gseNCG` currently only works with human, but not mouse.
