### ISSUE TITLE
Error dotplot: Unknown scale type

### ISSUE THREAD

**Issue by Alina-Ba** [GuangchuangYu/enrichplot#218]
I got an error using the dotplot() function related to the color scale.

Error in `scale_color_continuous()`:
! Unknown scale type
Backtrace:
 1. enrichplot::dotplot(MSigDB, showCategory = 10)
 2. enrichplot::dotplot(MSigDB, showCategory = 10)
 3. enrichplot .local(object, ...)
 4. enrichplot:::dotplot.enrichResult(...)
 5. ggplot2::scale_color_continuous(...)

Does anyone know what could be the problem?

Thank you!!

**Comment by Alina-Ba** [comment]
For example the code from the tutorial:

**Comment by Alina-Ba** [comment]
For example the code from the tutorial: https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html

**Comment by Alina-Ba** [comment]
For example the code from the tutorial: https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html 

library(DOSE)
data(geneList)
de <- names(geneList)[abs(geneList) > 2]

edo <- enrichDGN(de)
library(enrichplot)
dotplot(edo, showCategory=20) 

Error in `scale_color_continuous()`:
! Unknown scale type: "Blues"
ℹ Use either "gradient" or "viridis"
Backtrace:
 1. enrichplot::dotplot(edo, showCategory = 20)
 2. enrichplot::dotplot(edo, showCategory = 20)
 3. enrichplot (local) .local(object, ...)
 4. enrichplot:::dotplot.enrichResult(...)
 5. ggplot2::scale_color_continuous(low = "red", high = "blue", name = color, guide = guide_colorbar(reverse = TRUE))
Error in scale_color_continuous(low = "red", high = "blue", name = color, :

ℹ Use either "gradient" or "viridis"

**Comment by huerqiang** [comment]
It works well in my R. Please use the latest version of the packages, preferably with screenshots of the running process and results.
![image](https://user-images.githubusercontent.com/48857018/206335677-7ec5cee9-dabf-4050-804e-1bbdc967bd23.png)
