### ISSUE TITLE
UseMethod("rescale") error using cnetplot() function

### ISSUE THREAD

**Issue by lmanchon** [GuangchuangYu/enrichplot#251]
cnetplot() failed with:

Error in UseMethod("rescale") : 
  no method for 'rescale' applicable to an object of class "AsIs"

with R version 4.1.2
i have installed ggnewscale package but nothing change.

idea ?

**Comment by guidohooiveld** [comment]
Please use the latest version of `clusterProfiler` and `enrichplot`.

See: https://github.com/YuLab-SMU/enrichplot/issues/244

**Comment by lmanchon** [comment]
direct links to download the latests version ?

**Comment by guidohooiveld** [comment]
Mmm,
R-4.3.x: https://cran.r-project.org/
Bioconductor v3.17: https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html and https://bioconductor.org/packages/release/bioc/html/enrichplot.html

**Comment by lmanchon** [comment]
okay, i understand now, i need R version R-4.3.
i have 4.1.2.

**Comment by guidohooiveld** [comment]
Yep! Sorry if that was not immediately clear to you...
