### ISSUE TITLE
Feature Request: Enhancements for cnetplot Function in enrichplot Package

### ISSUE THREAD

**Issue by jacobHog** [GuangchuangYu/enrichplot#253]
Hello,

Thank you for developing the valuable tools for enrichment analysis. I am writing to request the addition of a feature in the cnetplot function from the enrichplot package.

**Label Genes Shared Between Groups**: I kindly request the inclusion of a parameter that allows users to label genes that are shared between groups of terms in the cnetplot function. This would enhance the interpretability of the results.

**Filter Genes by Log2FC Value**: Additionally, it would be immensely helpful to have a parameter that enables users to label only those genes with a log2FC value exceeding a specified threshold. This feature would provide more flexibility in customizing the visualization.

These additions would further empower users to extract meaningful insights from the tool. Thank you for considering these enhancements.

Best regards,

**Comment by GuangchuangYu** [comment]
supported with <https://github.com/YuLab-SMU/ggtangle/commit/9213bd244f7c1ed6641c76c8e5df1529efb25eff>

```
library(ggtangle)
library(ggplot2)

set.seed(123)
x <- list(A = letters[1:10], B=letters[5:12], C=letters[sample(1:26, 15)])

p1 <- cnetplot(x)
p2 <- cnetplot(x, node_label="share")
p3 <- cnetplot(x, node_label="exclusive")

set.seed(123)
d <- setNames(rnorm(26), letters)
p4 <- cnetplot(x, foldChange=d) + 
    scale_color_gradient2(name='associated data', low='darkgreen', high='firebrick')


p5 <- cnetplot(x, foldChange=d, node_labe = ">1") + 
    scale_color_gradient2(name='associated data', low='darkgreen', high='firebrick')


p6 <- cnetplot(x, foldChange=d, hilight=c("B", "C")) + 
    scale_color_gradient2(name='associated data', low='darkgreen', high='firebrick')

aplot::plot_list(p1, p2, p3, p4, p5, p6, ncol=3)
```

![image](https://github.com/user-attachments/assets/ac4946b2-208d-41fe-9cf5-3512a6f45bdc)

**Comment by jacobHog** [comment]
Hi,

Thank you for creating this solution.

I want to highlight the genes with a negative fold change by using node_label "<-2" but the argument throws an error. 
To my understanding the only acceptable inputs for node_label is "gene", "category", "all", "none" ">x" where x is any number. But how do I use the negative numbers?

I am using bioconductor-clusterprofiler=4.14.0
