### ISSUE TITLE
Help with the new gradient colors

### ISSUE THREAD

**Issue by Shashankti** [GuangchuangYu/enrichplot#258]
Dear Support team,

Thank you for the package and the tools. I was looking at the recent update regarding the new colors for the plots. I would like to use the gradient for other plot objects(ggplot and complexHeatmap). I looked at the helper functions `set_enrichplot_color` which is used in the package, however I am struggling to understand how to implement this color gradient with `scale_fill_gradient` or `colorRamp2`.

Thank you for your help.

**Comment by jtutz** [comment]
Same here! I'm having problems changing the color gradient of the dotplot. 

Really appreciating the package!

**Comment by huerqiang** [comment]
The `set_enrichplot_color()` is used to set default colors for gg objects that are applicable for enrichplot, for example: 
```r
    p <- ggplot(df, aes_string(x=x, y="Description", size=size, fill=colorBy)) +
        geom_point() +
        aes(shape = I(enrichplot_point_shape)) + 
        # scale_fill_continuous(name = color) +
        set_enrichplot_color(type = "fill", name = color) 
```

**Comment by Shashankti** [comment]
Thank for the help
