### ISSUE TITLE
enhancement: cnetplot gene vs gene set node aesthetics customization

### ISSUE THREAD

**Issue by kimsjune** [GuangchuangYu/enrichplot#266]
Hello,

It would be nice to be able to pass font face and colour to customize gene and gene set node labels separately. This would help readers to discern between genes and gene sets. These options are already available with `geom_node_text`, but I'm unable to figure out how to group labels into genes vs gene sets and edit the code myself. Thank you.

SJK

**Comment by GuangchuangYu** [comment]
```
library(ggtangle)
set.seed(123)
x <- list(A = letters[1:10], B=letters[5:12], C=letters[sample(1:26, 15)])

cnetplot(x, node_label = 'none') + 
    geom_cnet_label(node_label = 'category', fontface = 'bold', size=10) +
    geom_cnet_label(node_label = 'item', color='firebrick', size=5)
```
![image](https://github.com/user-attachments/assets/79a58fb7-5846-4c7e-aa90-1786bbf0f62d)
