### ISSUE TITLE
add color setting for add_node_label function

### ISSUE THREAD

**Issue by yiluyucheng** [GuangchuangYu/enrichplot#267]
Hi,

Thanks for developing the enrichplot package, I found it is very useful!  When I was using the cnetplot function to plot Gene-Concept Network, I found there are no parameters to set the color of node labels. I wander would you consider adding a new parameter for this? Thanks.

Best,
WYC

**Comment by GuangchuangYu** [comment]
Now you can use ` geom_cnet_label` to adjust details for node labels. 

```r
library(ggtangle)
set.seed(123)
x <- list(A = letters[1:10], B=letters[5:12], C=letters[sample(1:26, 15)])

cnetplot(x, node_label = 'category') + geom_cnet_label(node_label = 'item', color='firebrick', size=10)
```

![image](https://github.com/user-attachments/assets/f28ff5b8-eb54-4e87-81cf-f12c597c5257)

**Comment by GuangchuangYu** [comment]
see also <https://github.com/YuLab-SMU/enrichplot/issues/266>.
