### ISSUE TITLE
Fractional Genes

### ISSUE THREAD

**Issue by DarioS** [GuangchuangYu/enrichplot#271]
It doesn't make sense to have 2.5 genes. Legend should automatically use meaningful category names.

![image](https://github.com/YuLab-SMU/enrichplot/assets/631218/9df296d8-6412-45e2-9f43-a4014fb969b3)

**Comment by GuangchuangYu** [comment]
can you provide a reproducible example?

**Comment by DarioS** [comment]
I can provide a reproducible example.

```r
library(enrichplot)
library(clusterProfiler)
library(DOSE)
set.seed(1234)
data(geneList)

geneList <- geneList[sort(sample(length(geneList), 100), decreasing = FALSE)]
edo <- gseDO(geneList, pvalueCutoff = 1)
dotplot(edo)
```

![image](https://github.com/user-attachments/assets/f4856f8b-928d-4e36-bcd5-255978771d91)

**Comment by GuangchuangYu** [comment]
fixed.
