### ISSUE TITLE
showCategory function throwing error within ridgeplot

### ISSUE THREAD

**Issue by ankurnaqib** [GuangchuangYu/enrichplot#290]
Hi,
I am trying to use the showCategory function within the ridgeplot. When I use it for dotplots, I give it a list of selected pathways like this

selected_pathways <- c("xenobiotic metabolic process","sulfur compound binding","lipid catabolic process","oxidoreductase activity","extracellular space")

and then I try to run the command -
ridgeplot(gseUpregulated, showCategory = selected_pathways) + labs(x = "enrichment distribution") + theme(text=element_text(size=10)) + theme(axis.text.y = element_text(size = 9))

This throws me an error

**Error in seq_len(n) : argument must be coercible to non-negative integer
In addition: Warning messages:
1: In seq_len(n) : first element used of 'length.out' argument
2: In ridgeplot.gseaResult(x, showCategory = showCategory, fill = fill,  :
  NAs introduced by coercion**

I checked and all the pathways that I mention within the selected_pathways vector are present in the gseUpregulated table. If I use a number instead of selected_pathways (showCategory = 10), it works but does not show the pathways I want to create a ridgeplot from. The selected pathways generally works when I use it within the dotplot function but is throwing me an error with ridgeplot. Can someone please help? Thank you.

**Comment by guidohooiveld** [comment]
What version of `enrichplot` are you using?

Could you provide a reproducible example?

**Comment by guidohooiveld** [comment]
i am asking because it should work:

https://github.com/YuLab-SMU/enrichplot/issues/193#issuecomment-1940689094

**Comment by ankurnaqib** [comment]
Thank you so much. I was able to install the updated version from source. And it worked.
