### ISSUE TITLE
goplot error with R 4.4

### ISSUE THREAD

**Issue by mhasoon** [GuangchuangYu/enrichplot#297]
I have recently updated my R to 4.4 and when I run goplot on my ORA object created with enrichGO I get the error:
_Error in AnnotationDbi::mget(id, GOANCESTOR) :
second argument must be an environment_

After reverting back to R version 4.3.3 I no longer get the error with the same object, so seems it might be a R 4.4 specific issue?

versions of packages as follows:
enrichplot ‘1.22.0’

Code used below:
```
GO_ORA <- enrichGO(gene = sig_set, 
             universe = background, 
             keyType = "SYMBOL", 
        OrgDb = org.Hs.eg.db,  
       ont = "BP", 
       pAdjustMethod = "BH", 
       pvalueCutoff = 0.05,        
       qvalueCutoff = 0.05)

goplot(GO_ORA) 
```

**Comment by guidohooiveld** [comment]
I can reproduce this error with the example data set:

```
> library(clusterProfiler)
> 
> data(geneList, package = "DOSE")
> de <- names(geneList)[1:100]
> yy <- enrichGO(de, 'org.Hs.eg.db', ont="BP", pvalueCutoff=0.01)
> goplot(yy)
Error in AnnotationDbi::mget(id, GOANCESTOR) : 
  second argument must be an environment
> 
> packageVersion("clusterProfiler")
[1] ‘4.12.6’
>
```

@GuangchuangYu : could you please have a look at this?

**Comment by guidohooiveld** [comment]
BTW, this issue has also been posted at the Git of `clusterProfiler`.

https://github.com/YuLab-SMU/clusterProfiler/issues/732

and

https://github.com/YuLab-SMU/clusterProfiler/issues/718

**Comment by guidohooiveld** [comment]
@GuangchuangYu : Thanks for also having a look at this issue.

Unfortunately the proposed fix doesn't work.... See below.

```
> library(clusterProfiler)
> library(enrichplot)
> 
> data(geneList, package = "DOSE")
> de <- names(geneList)[1:100]
> yy <- enrichGO(de, 'org.Hs.eg.db', ont="BP", pvalueCutoff=0.01)
> goplot(yy)
Error in storage.mode(mat) <- "integer" : 
  'list' object cannot be coerced to type 'integer'
> 
> 
> packageVersion("clusterProfiler")
[1] ‘4.12.6’
> packageVersion("enrichplot")
[1] ‘1.25.5’
> 
```

```
> traceback()
8: layout(data, ...)
7: as.data.frame(layout(data, ...))
6: setNames(as.data.frame(layout(data, ...)), c("x", "y"))
5: ggplot.igraph(g, layout = layout)
4: ggplot(g, layout = layout)
3: goplot.enrichResult(x, showCategory = showCategory, color = color, 
       layout = layout, geom = geom, ...)
2: goplot(yy)
1: goplot(yy)
> 
```

**Comment by guidohooiveld** [comment]
Addition:
I reverted back to the previous version, and using `enrichplot` `1.25.4` it works!
It thus seems that in `1.25.5` a(nother) bug is introduced resulting in the error mentioned in my post above. (`Error in storage.mode(mat) <- "integer" :  'list' object cannot be coerced to type 'integer'`)

```
> library(clusterProfiler)
> library(enrichplot)
> 
> data(geneList, package = "DOSE")
> de <- names(geneList)[1:100]
> yy <- enrichGO(de, 'org.Hs.eg.db', ont="BP", pvalueCutoff=0.01)
> goplot(yy)
> 
> packageVersion("enrichplot")
[1] ‘1.25.4’
> 
> packageVersion("clusterProfiler")
[1] ‘4.12.6’
>
```
![image](https://github.com/user-attachments/assets/2254a7ca-5698-42d0-8816-b819f0813ba5)

**Comment by GuangchuangYu** [comment]
fixed and you need to install github version of `ggtangle`, see also <https://github.com/YuLab-SMU/ggtangle/commit/caff5c005f26fd528f772ce92d9c811171d70c45>.

Otherwise, you can call `goplot(yy, layout=igraph::layout_nicely)`.

**Comment by guidohooiveld** [comment]
Thanks!; it is indeed working, but how to display the category names, and not ids?

```
> goplot(yy)
> packageVersion("enrichplot")
[1] ‘1.25.6’
> packageVersion("ggtangle")
[1] ‘0.0.4’
> 

```

![image](https://github.com/user-attachments/assets/a0effcfd-8e90-445a-a8b9-8437c12e295f)

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/enrichplot/issues/292#issuecomment-2445788948>.

**Comment by guidohooiveld** [comment]
For the archive:

 `goplot(yy, ID="{Description}")`

![image](https://github.com/user-attachments/assets/c86b07c0-01c9-4847-99b1-4881e3b2d0fd)



`goplot(yy, ID="{ID}")
`
![image](https://github.com/user-attachments/assets/23ffdef9-628e-4b13-901d-5ef16498be2b)



`goplot(yy, ID="{ID}\n{Description}")
`
![image](https://github.com/user-attachments/assets/3b607e1c-e99a-4368-8974-fc20bf1a3912)




```
> R.Version()$version.string
[1] "R version 4.4.2 (2024-10-31 ucrt)"
> packageVersion("clusterProfiler")
[1] ‘4.14.0’
> packageVersion("enrichplot")
[1] ‘1.26.1’
> 
```
