### ISSUE TITLE
installing enrichplot

### ISSUE THREAD

**Issue by GuangchuangYu** [GuangchuangYu/enrichplot#3]
Due to the submission of `enrichplot` to [Bioconductor](https://github.com/Bioconductor/Contributions/issues/567), which forces new submission to depend on devel version of R (3.5.0), the package was rejected to install on current release version of R.

I do want you guys to try this new package and you can follow these steps to install it.

## download the repo

`Download ZIP`, unzip it and rename `enrichplot-master` to `enrichplot`.

or simply using the following command:

```
git clone https://github.com/GuangchuangYu/enrichplot.git
```

## downgrade R version dependency

in MacOS:

```
cd enrichplot
sed -i "" 's/3.5.0/3.4.0/g' DESCRIPTION
cd ..
```

in Linux:
```
cd enrichplot
sed -i 's/3.5.0/3.4.0/g' DESCRIPTION
cd ..
```

or open `enrichplot/DESCRIPTION` using your favorite text editor and replace `3.5.0` to `3.4.0`. 
 
## install using `devtools`

```
Rscript -e 'devtools::install_local("enrichplot")'
```

**Comment by GuangchuangYu** [comment]
after installing `enrichplot`, you can install github version of `DOSE` and `clusterProfiler` via:

```r
devtools::install_github(c("GuangchuangYu/DOSE", "GuangchuangYu/clusterProfiler"))
```

**Comment by GuangchuangYu** [comment]
now `enrichplot`  depends on R >= 3.4.0

**Comment by mendiburu** [comment]
Hi, I have done all the steps that you suggest but I still have problems to install enrichplot. I have changed the version to 3.4.0 in the description folder but is still giving the same message: 
package ‘enrichplot’ is not available (for R version 3.4.3) 
Could you help me with this problem? Thank you very much

**Comment by akshaya4r** [comment]
Hi,
I've been trying to install enrichplot. I have R 3.4.3. I followed these instructions and get the following error.

`Installing enrichplot
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpugcXRV/file24d331ab7f9b/enrichplot'  \
  --library='/home/ar/R/x86_64-redhat-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘enrichplot’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘DOSE’ 3.2.0 is being loaded, but >= 3.5.1 is required
ERROR: lazy loading failed for package ‘enrichplot’
* removing ‘/home/ar/R/x86_64-redhat-linux-gnu-library/3.4/enrichplot’

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: q("no", status = status, runLast = FALSE)
 2: do_exit(status = status)
 3: do_exit_on_error()
 4: errmsg(msg, " for package ", sQuote(pkg))
 5: pkgerrmsg("lazy loading failed", pkg_name)
 6: do_install_source(pkg_name, instdir, pkg, desc)
 7: do_install(pkg)
 8: tools:::.install_packages()
An irrecoverable exception occurred. R is aborting now ...
/usr/lib64/R/bin/INSTALL: line 34:  9450 Done                    echo 'tools:::.install_packages()'
      9451 Segmentation fault      (core dumped) | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Installation failed: Command failed (139)`

I have the same error when trying to install from bioconductor as well.

**Comment by GuangchuangYu** [comment]
> namespace ‘DOSE’ 3.2.0 is being loaded, but >= 3.5.1 is required

pls update all your pkgs to latest release version.
