### ISSUE TITLE
Comparecluster Emapplot Pie Node Size Error

### ISSUE THREAD

**Issue by mj-kamal** [GuangchuangYu/enrichplot#301]
In brief, the `size_category` argument doesn't work for emapplots using comparecluster objects when displaying nodes as pie graphs. I'm trying to decrease the pie graph - node size (or scale everything else up to make the nodes look smaller) and I've tried a few different things with no success. I should note that this wasn't an issue with a previous version of enrichplot (1.20.3). 

Example code below: 

```
#gene_list is a list with 3 elements containing gene entrezids
compare_cluster_results <- compareCluster(
  geneCluster = gene_list, 
  fun = "enrichGO",
  OrgDb = org.Mm.eg.db,
  ont = "BP",           
  pAdjustMethod = "BH", 
  qvalueCutoff = 0.05
)

cc_PT <- pairwise_termsim(compare_cluster_results)

emapplot(
    cc_PT,
    showCategory = 35,
    size_category = 0.5,
    pie = "count", 
    group = TRUE)

```

**Comment by GuangchuangYu** [comment]
```
emapplot(
    cc_PT,
    showCategory = 35,
    size_category = 0.5,
    pie = "count", 
    group = TRUE)
```

![image](https://github.com/user-attachments/assets/bf47a9f4-b273-4d60-a042-257937c770ee)
