### ISSUE TITLE
The code in ridgeplot might be wrong

### ISSUE THREAD

**Issue by Xiaoke-666** [GuangchuangYu/enrichplot#303]
Hi, thanks for providing this wonderful tool. I know this is a development version, but I found this line of code might be wrong. 
https://github.com/YuLab-SMU/enrichplot/blob/2898ac367d5956ecf031386820cc70294be5cd47/R/ridgeplot.R#L54
I guess the x$ID only gives enriched (significantly changed) pathway but x@geneSets gives all pathways in the database, right? So, this code might lead to incorrect pathways in x@geneSets to be selected. It should be: gs2id <- x@geneSets[names(x@geneSets) %in% selected] isn't it?

**Comment by GuangchuangYu** [comment]
thanks. This is indeed more safe.
