### ISSUE TITLE
goblot error: "Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :    行类不对

### ISSUE THREAD

**Issue by JiaruiMi** [GuangchuangYu/enrichplot#5]
Hi, Guangchuang,

I downloaded your latest packages (clusterprofiler, DOSE and enrichplot) from you github repository and checked the goplot. I used your embedded dataset (copy and paste) and check the goplot function. The code is as follows:

CODE:
```r
> library(clusterProfiler)
> data(geneList, package="DOSE")
> de <- names(geneList)[abs(geneList) > 2]
> ego <- enrichGO(de, OrgDb = "org.Hs.eg.db", ont="BP", readable=TRUE)
> library(enrichplot)
> goplot(ego)

ERROR MESSAGE:
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  行类不对
```

My R version is 3.4.3.

Thanks!

**Comment by GuangchuangYu** [comment]
reinstall `enrichplot` and try again.

should works smoothly with `v >= 0.99.13`
