### ISSUE TITLE
DOSE FOR ENRICHPLOT AND CLUSTERPROFILER

### ISSUE THREAD

**Issue by mendiburu** [GuangchuangYu/enrichplot#6]
Hi, I am trying to use two different packages, clusterProfiler and enrichplot; the first one works with DOSE 3.4.0 but not wit 3.5.1 (dotplot problem) and enrichplot works with DOSE 3.5.1 but not with 3.4.0. Could you help me to solve this problem? Thank you very much.

**Comment by GuangchuangYu** [comment]
you need to also install github version of `clusterProfiler`, i.e. v >=3.7.1.

**Comment by mendiburu** [comment]
Thank you very much for your help. Problem solved
