### ISSUE TITLE
package ‘enrichplot’ is not available (for R version 3.4.0) 

### ISSUE THREAD

**Issue by asmagen** [GuangchuangYu/enrichplot#8]
Hello,

Do you know how can I install the package on R 3.4.0?
I get the following error when trying to install through bioconductor:
package ‘enrichplot’ is not available (for R version 3.4.0) 

Thanks,
Assaf

**Comment by GuangchuangYu** [comment]
R 3.5 is required for Bioconductor 3.7

**Comment by asmagen** [comment]
Is there any workaround to install it on R 3.4.0 then?
